theme: jekyll-theme-minimal
title: 'Differential Expression and Enrichment Analysis in R'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Preliminaries
  - title: Before the course
    url: preliminaries/before
  - title: File downloads
    url: examples
